### ISSUE TITLE
Review FactoryGirl

### ISSUE THREAD

**Issue by rubyjiun** [KaterinaSav/sample_app#14]
1 https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#configure-your-test-suite
Эта настройка в rspec поможет убрать слово FactoryGirl из спеков.

## before

```ruby
describe "profile page" do
  let(:user) { FactoryGirl.create(:user) }
```

## after
```ruby
describe "profile page" do
  let(:user) { create(:user) }
```

2 Лучше создать папку factories и там создавать файлы с именами моделей, т.к. фабрик в одном проекте может быть очень много
https://github.com/KaterinaSav/sample_app/blob/develop/spec/factories.rb

@KaterinaSav как пофиксишь скинь здесь ссылку на пул реквест.

**Comment by KaterinaSav** [comment]
@rubyjiun https://github.com/KaterinaSav/sample_app/pull/15
